config/routes.rb
TestTask::Application.routes.draw do
  resources :ingredients

  root to: "recipes#index"

  resources :recipes 
  

end

app/models/concerns/ingredients_handler.rb
module IngredientsHandler
	extend ActiveSupport::Concern

	included do 
		attr_accessor :added_ingredients

		before_save  do 
			@availableIngredients = Ingredient.all.to_a
		end

		after_save :checkIngredientsAssociation,on:[:create,:update]
	end

protected
	def checkIngredientsAssociation
		currentIngredients = ingredients.to_a
		currentIngredientsIds  = currentIngredients.map{|item| item.id.to_s}
		addedIngredients = added_ingredients
		# Delete remove ingredients
		if addedIngredients
			(currentIngredients & @availableIngredients).each do |item|
				unless(addedIngredients.include? item.id.to_s)
					ingredients.delete(item)
				end
			end

			# Insert added ingredients in the association
			(addedIngredients - currentIngredientsIds).each do |item|
				ingredient = Ingredient.find(item.to_i)
				ingredients << ingredient
			end
		end	
	end



end




	
	

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

	has_and_belongs_to_many :recipes

	validates :name, uniqueness: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	include IngredientsHandler
	
	has_and_belongs_to_many :ingredients

	accepts_nested_attributes_for :ingredients, reject_if: lambda{|a| a[:name].blank?}

	validates :title, uniqueness: true

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:ingredients]
      @recipes = Recipe.joins(:ingredients).where("ingredients.name" => params[:ingredients]).uniq 
    else
      @recipes = Recipe.all    
    end
   
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all.to_a.map{|i| {ingredient: i , added: false}}
    
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
      @ingredients = Ingredient.all.to_a.map {|i| {ingredient:i,added: @recipe.ingredients.to_a.include?(i)}} 
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description,added_ingredients:[],ingredients_attributes:[:id,:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def template_fields(f,association)
		new_object  = f.object.class.reflect_on_association(association).klass.new
		template = f.fields_for(association, new_object, child_index: "replaceable_new_#{association}") do |builder|
					render(association.to_s.singularize+"_fields",f: builder)
		end
		template.to_s
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_filter_form.html.erb
<div id="filter_form_container">
	<%=form_tag({controller:"recipes",action:"index"}, method:"get",id:"filter_form") do%>
		<div class="row">
			<%Ingredient.all.to_a.each do |item|%>
				<p data-key='<%=item.name%>' class="filter item col-sm-1 <%= 'selected' if params[:ingredients] && params[:ingredients].include?(item.name) %>">
					<%=item.name.capitalize%>
				</p>
			<%end%>
		</div>
		<div class="row">
			<button type="submit" class="btn btn-default col-sm-12">Filter</button>
		</div>
	<%end%>
</div>

app/views/recipes/_form.html.erb
<%= form_for @recipe, html:{} do |f| %>
  <% if @recipe.errors.any? %>
  
    <div class= "alert alert-danger" role="alert">
      <div id="error_explanation">
        <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title,class:"col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :title,class:'form-control' %>
    </div>

  </div>
  <div class="form-group">
    <%= f.label :description,class:"col-sm-2 control-label"%>
    <div class="col-sm-8">
      <%= f.text_area :description,class:'form-control' %>
    </div>

  </div>
  <div class="field" id="added_ingredients" style="display:none;">

  </div>
  <div class="form-group" id="ingredients_field" data-template='<%=template_fields(f,:ingredients)%>'>
    <label class="col-sm-2 control-label">Available Ingredients</label>
    <div class="col-sm-8">
      <%@ingredients.each do |item|%>
          <div class="ingredient">
            <span class="col-sm-1"><%=item[:ingredient].name.capitalize%></span>
            <span class="col-sm-1"><input data-id="<%=item[:ingredient].id%>" data-name="<%=item[:ingredient].name%>" type="checkbox" <%='checked' if item[:added]%>></span>
          </div>
       <%end%>
       <div class="form-group col-sm-8 col-sm-offset-1">
         <button type="button" id = "add_new_ingredient" class="btn btn-default icon remove_ingredient">
              <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 
              Add More
          </button>
        </div>
    </div>
       
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit "Done", class:"btn btn-default col-sm-8"%>
    </div>
  </div>
<% end %>


<%=javascript_tag do %>
  $(function(){
    $("form").addClass("form-horizontal");
  });
<%end%>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-group">
	<%=f.hidden_field :id%>
	<%=f.label :name,class:"col-sm-1 control-label"%>
	<div class="col-sm-6">
      <%=f.text_field :name, class:'form-control'%>
    </div>
    <button type="button" class="btn btn-default icon remove_ingredient"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> Remove</button>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h3>Filter by Ingredients</h3></div>
  <div class="panel-body">
    <%=render 'filter_form'%>
  </div>
</div>

  

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title.capitalize %></td>
        <td><%= recipe.description.capitalize%></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<nav>
  <ul class="pagination">
    <li>
      <%= link_to 'New Recipe', new_recipe_path %>
    </li>
  </ul>
</nav>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<nav>
  <ul class="pagination">
    <li>
    	<%= link_to 'Back', recipes_path %>
	</li>
  </ul>
</nav>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Recipe</h3>
  </div>
  <div class="panel-body">
	  	<p>
		  <strong>Title:</strong>
		  <%= @recipe.title.capitalize %>
		</p>

		<p>
		  <strong>Description:</strong>
		  <%= @recipe.description.capitalize %>
		</p>
  </div>
  <ul class="list-group">
  		<h4>Ingredients</h4>
		<%@recipe.ingredients.each do |item|%>
			<li class="list-group-item"><%=item.name.capitalize%></li>
		<%end%>
	</ul>
</div>

<nav class="col-sm-10">
  <ul class="pagination">
    <li>
    	<%= link_to 'Edit', edit_recipe_path(@recipe) %>
	</li>
    <li>
    	<%= link_to 'Back', recipes_path %>
	</li>
  </ul>
</nav>